### ISSUE TITLE
Add Google Sign-in to the backend

### ISSUE THREAD

**Issue by isaacgarza** [isaacgarza/spend-smart#45]
As a user, I want to be able sign-in/sign-up using Google so that I do not have to remember another password and use an already trusted source for login credentials.

**Acceptance Criteria**
- Google sign-in functionality added to the backend

**Definition of Done**
- Google sign-in functional
- Google sign-up functional

**Tasks**
- [x] Update user in DDL to support social sign-in
- [x] Add security dependencies for oauth
- [x] Add properties for google sign-in
- [x] Update the user DTO and table to match the DDL changes
- [x] Add get user by email
- [x] Add WebSecurityConfiguration for ouahth2 authentication
- [x] Add all classes needed for oauth2 authentication using google
